### ISSUE TITLE
iPad Pro - unavailable for Lightning and NFC

### ISSUE THREAD

**Issue by S474N** [Yubico/yubikit-ios#60]
iPad Pro 2018 (with USB-C) with iOS 14.1 and have this warning:

`This version of iOS does not support operations with the Yubikey for Lightning nor over NFC`

**Comment by jensutbult** [comment]
This is expected. The iPad Pro has neither NFC nor a Lightning port and since these are the only Apple approved ways for an iOS app to communicate with the YubiKey the SDK does not support the iPad Pro. The YubiKey 5C will support FIDO in Safari though which probably just adds more confusion to the issue.
