### ISSUE TITLE
Request for Xamarin support

### ISSUE THREAD

**Issue by RedBlue1776** [Yubico/yubikit-ios#8]
To best integrate with my project, I would need Xamarin.iOS support, or ideally Xamarin Forms support.

Would you kindly put this on the roadmap?

**Comment by imakhalova** [comment]
@RedBlue1776  thank you for your request. Can you please specify which functionality of YubiKey you're interested in, what scenarios trying to cover?

**Comment by imakhalova** [comment]
Closing issue as there is not enough information to create a task.
If you'd like to provide more information on what Yubico can provide for you so that you can easier integrate with YubiKey, I'd suggest to join developer program https://www.yubico.com/why-yubico/for-developers/developer-program/ and share details: your app, how think YubiKey can be used within it. This will help us to provide you with better support, personalized experience and you'll be able to try pre-release versions.
